spring:
  application:
    name: backend

  session:
    jdbc:
      initialize-schema: never
      table-name: SPRING_SESSION
  # The h2 database is automatically registered as a datasource

server:
  servlet:
    session:
      timeout: 30m # default
      cookie:
        http-only: true
        secure: true
        same-site: strict

app:
  my-config:
    user-repository: database